Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2020-07, with the labels that each got.

#193 Chore: Replace scopelint with exportloopref
  .circleci/config.yml
  .golangci.toml
Labels: chore

#198 data: wide time series frame field sorting
  data/frame_test.go
  data/time_series.go
  data/time_series_field_sort_test.go
  data/time_series_test.go
  data/vector.go
Labels: dataframe

#197 add experimental golden data response checking
  experimental/golden_response_checker.go
  experimental/golden_response_checker_test.go
  experimental/testdata/sample.golden.txt
Labels: enhancement

#200 data: add SetMeta() to Frame
  data/arrow_test.go
  data/frame.go
Labels: dataframe

#201 data: provide keys for wide frame series field sort
  data/time_series.go
  data/time_series_field_sort_test.go
Labels: dataframe

#204 data: check field length in MarshalArrow
  data/arrow.go
  data/arrow_test.go
  data/frame.go
Labels: arrow, dataframe
