Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2020-04, with the labels that each got.

#86 include common magefile package
  build/README.md
  build/common.go
  go.mod
  go.sum
Labels: type/build

#113 Add .editorconfig
  .editorconfig
Labels: chore

#114 Chore: Upgrade Go; run go mod tidy
  go.mod
  go.sum
Labels: chore

#122 data/dsql: move sql pieces to subpackage
  backend/data.go
  data/sqlutil/sql.go
  data/sqlutil/sql_test.go
Labels: dataframe

#123 backend: code docs for PluginConfig
  backend/common.go
Labels: documentation

#125 Chore: Upgrade JS dependencies
  tools/arrow-inspect/yarn.lock
Labels: chore

#116 Add build utility functions
  build/utils/copy.go
  build/utils/copy_test.go
  build/utils/exists.go
  build/utils/exists_test.go
Labels: chore

#132 backend: fix panic in convertToProtobuf QueryDataResponse
  backend/convert_to_protobuf.go
Labels: bug

#144 Chore: Convert to Mage
  .circleci/config.yml
  .golangci.toml
  Magefile.go
  Makefile
  data/vector.go
  genproto/pluginv2/backend.pb.go
Labels: chore

#145 Improve debugger target
  build/common.go
Labels: chore

#143 backend: Move default logger to backend/log
  backend/grpcplugin/serve.go
  backend/log.go
  backend/log/log.go
Labels: chore

#147 data: fix NewFrameInputConverter example typos
  data/conversion_input_test.go
Labels: bug, documentation

#151 data: remove Frame.String() method
  data/conversion_input_test.go
  data/frame.go
  data/frame_test.go
  data/sqlutil/sql_test.go
Labels: dataframe

#154 chore: cleanup redudant composite literals
  backend/resource_adapter_test.go
  data/arrow_test.go
  data/conversion_input_test.go
  data/frame_test.go
  data/time_series_test.go
Labels: chore

#153 data: remove frame.AppendRowSafe
  data/frame.go
  data/frame_test.go
  data/vector.go
Labels: dataframe

#155 data: add support for Duration type in Frame
  data/arrow.go
  data/arrow_column_builders.go
  data/arrow_test.go
  data/field.go
  data/frame_test.go
  data/generic_nullable_vector.go
  data/generic_vector.go
  data/nullable_vector.gen.go
  data/testdata/all_types.golden.arrow
  data/vector.gen.go
  data/vector.go
Labels: dataframe

#156 build: go generate on data package via mage
  Magefile.go
  README.md
Labels: type/build
