Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2020-06, with the labels that each got.

#186 data: code docs - note on not using StringTable for testing
  data/frame.go
Labels: documentation

#185 data: (breaking) FrameMeta change custom property to interface
  data/frame_meta.go
Labels: dataframe

#189 Build: Disable cgo
  build/common.go
Labels: chore, type/build

#184 Build: Support building on Windows
  build/common.go
  build/common_unix.go
  go.mod
Labels: bug

#190 Update arrow dependency
  go.mod
  go.sum
Labels: arrow, dataframe
