Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2021-01, with the labels that each got.

#246 Chore: Add thelper linter
  .circleci/config.yml
  .golangci.toml
  backend/convert_from_protobuf_test.go
  build/utils/copy_test.go
  data/frame_test.go
Labels: chore

#239 remove Transform code
  backend/grpcplugin/grpc_transform.go
  backend/grpcplugin/serve.go
  backend/serve.go
  backend/transform.go
  backend/transform_adapter.go
  genproto/pluginv2/backend.pb.go
  proto/backend.proto
Labels: chore

#249 Add datasource UID field
  backend/common.go
  backend/convert_from_protobuf.go
  backend/convert_from_protobuf_test.go
  genproto/pluginv2/backend.pb.go
  proto/backend.proto
Labels: enhancement

#253 Chore: Enable dependabot
  .github/dependabot.yml
Labels: chore

#263 FieldConfig: fix json settings for ValueMapping
  data/field_config.go
  data/field_config_test.go
Labels: bug
