Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2022-11, with the labels that each got.

#544 DataResponse: Add status code
  backend/convert_from_protobuf.go
  backend/convert_from_protobuf_test.go
  backend/convert_to_protobuf.go
  backend/convert_to_protobuf_test.go
  backend/data.go
  backend/json.go
  backend/json_test.go
  backend/status.go
  experimental/golden_response_checker_test.go
  experimental/testdata/frame-custom-meta.golden.jsonc
  experimental/testdata/frame-empty-custom-meta.golden.jsonc
  experimental/testdata/frame-json.jsonc
  experimental/testdata/frame-no-meta.golden.jsonc
  experimental/testdata/frame-non-custom-meta.golden.jsonc
  experimental/testdata/single-json-frame.golden.jsonc
  experimental/testdata/single-json-framer.golden.jsonc
  genproto/pluginv2/backend.pb.go
  genproto/pluginv2/backend_grpc.pb.go
  proto/backend.proto
Labels: enhancement

#552 Dataplane Contract: Add section on Error Responses
  data/contract_docs/contract.md
Labels: documentation, area/dataplane

#507 Contract: add heatmap format docs
  data/contract_docs/contract.md
  data/contract_docs/heatmap.md
Labels: area/dataplane

#557 Contract Docs: Remove "Proposal"
  data/contract_docs/contract.md
Labels: documentation, area/dataplane

#559 Contract Docs: (Chore) Some linting and timestamp formatting for heatmap
  data/contract_docs/contract.md
  data/contract_docs/heatmap.md
Labels: documentation, chore, area/dataplane

#558 Contract Docs: Add README.md symlink to contract.md
  data/contract_docs/README.md
Labels: documentation, chore, area/dataplane

#568 Dataplane: Spec - Update NoData to allow for no frames
  data/contract_docs/contract.md
Labels: documentation, area/dataplane
