Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2023-04, with the labels that each got.

#663 Tracing: Support multiple OTel propagators
  backend/httpclient/tracing_middleware_test.go
  backend/setup.go
  internal/tracerprovider/tracerprovider.go
  internal/tracerprovider/tracerprovider_test.go
Labels: enhancement, go

#664 Tracing: Add more details to HTTP Outgoing Request
  backend/httpclient/tracing_middleware.go
  go.mod
  go.sum
Labels: enhancement, go

#647 Data: Encode Nanosecond into JSON
  data/frame.go
  data/frame_json.go
  data/frame_json_test.go
  data/testdata/all_types.golden.json
Labels: dataframe, area/dataplane

#670 Data: (Docs) Update code example to be dataplane compliant
  data/frame_test.go
Labels: documentation, area/dataplane
