Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2023-03, with the labels that each got.

#645 Fix go manifest permissions
  build/common.go
Labels: bug

#646 Update developer-guide.md
  contribute/developer-guide.md
Labels: documentation

#641 Data: Add TypeInfo method to Frame
  data/frame.go
Labels: dataframe, area/dataplane

#621 Backend plugin debug mode improvements
  backend/app/manage.go
  backend/datasource/manage.go
  backend/serve.go
  internal/standalone/standalone.go
  internal/standalone/standalone_test.go
  internal/standalone/testdata/GoLand/plugin.json
  internal/standalone/testdata/plugin/plugin.json
  internal/standalone/testdata/standalone-txt/standalone.txt
Labels: enhancement, go

#656 Chore: Downgrade kin-openapi to v0.112.0
  go.mod
  go.sum
Labels: chore, dependencies, go
