Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2023-10, with the labels that each got.

#757 Tracing: Set service version tracer attribute from compile-set build info
  backend/setup.go
Labels: enhancement, go

#761 Use random port in TestTenantWithPluginInstanceManagement
  internal/tenant/tenanttest/tenant_test.go
Labels: bug, chore, go

#759 Fix tracing middleware data race when no tracer is provided
  backend/httpclient/tracing_middleware.go
  backend/httpclient/tracing_middleware_test.go
Labels: bug, go

#758 Add -buildinfo and -version flags
  backend/app/manage.go
  backend/datasource/manage.go
  internal/buildinfo/buildinfo.go
Labels: enhancement, go

#754 PDC: Configure proxy with info from request
  backend/common.go
  backend/common_test.go
  backend/config.go
  backend/data_adapter.go
  backend/data_adapter_test.go
  backend/datasource/serve_example_test.go
  backend/diagnostics_adapter.go
  backend/httpclient/http_client.go
  backend/httpclient/options.go
  backend/proxy/options.go
  backend/proxy/secure_socks_proxy.go
  backend/proxy/secure_socks_proxy_test.go
  backend/resource_adapter.go
  backend/stream_adapter.go
Labels: enhancement

#771 Ensure config map is not nil
  backend/config.go
Labels: bug

#772 Return empty Grafana config from context if is nil
  backend/config.go
  backend/config_test.go
Labels: bug

#769 Contextual tracer from multi-tenancy
  backend/tracing/contextual_tracer.go
  backend/tracing/tracing.go
Labels: enhancement

#775 Add contextual logger (log.FromContext)
  backend/data_adapter.go
  backend/diagnostics_adapter.go
  backend/log.go
  backend/log/context.go
  backend/log/context_test.go
  backend/log/log.go
  backend/log/log_test.go
  backend/log_test.go
  backend/resource_adapter.go
  backend/stream_adapter.go
Labels: enhancement, go

#779 Chore: Fix lint warnings with golangci-lint version 1.54.2
  .golangci.toml
  backend/setup.go
  build/utils/copy.go
  data/time_series.go
Labels: chore, go

#780 Chore: CI: Bump grafana-plugin-ci image to 1.9.5
  .drone.yml
  go.mod
Labels: chore

#793 Chore: Fix lint warnings with golangci-lint v1.55.1
  .golangci.toml
  data/frame_json.go
  experimental/authclient/authclient_test.go
  experimental/e2e/proxy_test.go
  experimental/oauthtokenretriever/sign_test.go
Labels: chore, go
