Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2023-02, with the labels that each got.

#597 Dataframe: Add TypeVersion property to FrameMeta
  data/contract_docs/contract.md
  data/contract_docs/heatmap.md
  data/contract_docs/numeric.md
  data/contract_docs/timeseries.md
  data/frame_meta.go
  data/frame_type.go
  experimental/sdata/common.go
  experimental/sdata/numeric/long.go
  experimental/sdata/numeric/multi.go
  experimental/sdata/numeric/numeric.go
  experimental/sdata/numeric/numeric_test.go
  experimental/sdata/numeric/util.go
  experimental/sdata/numeric/wide.go
  experimental/sdata/reader/play_test.go
  experimental/sdata/reader/reader.go
  experimental/sdata/timeseries/long.go
  experimental/sdata/timeseries/long_test.go
  experimental/sdata/timeseries/multi.go
  experimental/sdata/timeseries/multi_test.go
  experimental/sdata/timeseries/series.go
  experimental/sdata/timeseries/series_test.go
  experimental/sdata/timeseries/util.go
  experimental/sdata/timeseries/wide.go
  experimental/sdata/timeseries/wide_test.go
Labels: area/dataplane

#606 Data: Frame.Meta.TypeVersion from pointer to non-pointer
  data/frame_meta.go
  data/frame_type.go
  data/testdata/all_types.golden.arrow
  data/testdata/all_types.golden.json
  experimental/sdata/numeric/long.go
  experimental/sdata/numeric/multi.go
  experimental/sdata/numeric/numeric_test.go
  experimental/sdata/numeric/util.go
  experimental/sdata/numeric/wide.go
  experimental/sdata/reader/reader.go
  experimental/sdata/timeseries/long.go
  experimental/sdata/timeseries/long_test.go
  experimental/sdata/timeseries/multi.go
  experimental/sdata/timeseries/multi_test.go
  experimental/sdata/timeseries/series_test.go
  experimental/sdata/timeseries/util.go
  experimental/sdata/timeseries/wide.go
  experimental/sdata/timeseries/wide_test.go
  experimental/testdata/frame-custom-meta.golden.jsonc
  experimental/testdata/frame-empty-custom-meta.golden.jsonc
  experimental/testdata/frame-non-custom-meta.golden.jsonc
Labels: dataframe, area/dataplane

#610 Generates a go_plugin_build_manifest file when building a plugin
  build/common.go
  build/utils/manifest.go
Labels: type/build, go

#618 Data: Document no nil entires in Fields / Frames
  data/frame.go
Labels: dataframe

#627 experimental/sdata: Add RefID to writers and readers
  experimental/sdata/numeric/long.go
  experimental/sdata/numeric/multi.go
  experimental/sdata/numeric/numeric.go
  experimental/sdata/numeric/numeric_test.go
  experimental/sdata/numeric/util.go
  experimental/sdata/numeric/wide.go
  experimental/sdata/reader/play_test.go
  experimental/sdata/timeseries/long.go
  experimental/sdata/timeseries/multi.go
  experimental/sdata/timeseries/multi_test.go
  experimental/sdata/timeseries/series.go
  experimental/sdata/timeseries/series_test.go
  experimental/sdata/timeseries/util.go
  experimental/sdata/timeseries/wide.go
  experimental/sdata/timeseries/wide_test.go
Labels: area/dataplane

#626 sdata/timeseries: fix bug in long on wrong field type
  experimental/sdata/timeseries/long.go
Labels: area/dataplane

#632 Data: Make (WIP) enums contain EnumItem
  data/arrow.go
  data/arrow_column_builders.go
  data/arrow_test.go
  data/field.go
  data/field_type.go
  data/field_type_enum.go
  data/frame_json.gen.go
  data/frame_json.go
  data/frame_json_test.go
Labels: dataframe, area/dataplane
