Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2024-04, with the labels that each got.

#944 SchemaBuilder: Fix enum value extraction
  experimental/schemabuilder/enums.go
  experimental/schemabuilder/enums_test.go
  experimental/schemabuilder/example/query.go
  experimental/schemabuilder/reflector.go
Labels: bug

#951 SQL: Check if `scanType` value is `nil`
  data/sqlutil/scanrow.go
Labels: bug, effort/small

#952 PDC: Fix env var config fallback
  backend/proxy/env.go
  backend/proxy/env_test.go
Labels: bug

#955 Set proxy options from context
  backend/common.go
  backend/common_test.go
Labels: enhancement
