Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2025-03, with the labels that each got.

#1253 Add support for forwarding HTTP headers for streaming requests
  backend/data.go
  backend/diagnostics.go
  backend/http_headers.go
  backend/resource.go
  backend/stream.go
Labels: enhancement

#1255 Support running nested plugins via standalone when debugging
  internal/standalone/standalone.go
  internal/standalone/standalone_test.go
  internal/standalone/testdata/dist/plugin.json
  internal/standalone/testdata/plugin/datasource/plugin.json
  internal/standalone/testdata/plugin/plugin.json
Labels: enhancement

#1252 Add support for Arrow string view type
  data/arrow.go
  data/arrow_test.go
Labels: enhancement, arrow, area/dataplane

#1267 Add mage target for custom backend builds
  build/common.go
Labels: type/build

#1268 Add mage target for running tests with race detector
  build/common.go
Labels: enhancement
