Repository grafana/grafana-plugin-sdk-go, pull requests merged in 2025-01, with the labels that each got.

#1163 Enrich errors with error source using grpc status package
  backend/data_adapter.go
  backend/data_adapter_test.go
  backend/error_source.go
  experimental/status/status_source.go
  experimental/status/status_source_test.go
Labels: enhancement

#1188 Do not log error when standlone.txt does not exist
  internal/standalone/standalone.go
Labels: chore

#1208 data: Add NilAt method to Field and Frame
  data/field.go
  data/field_test.go
  data/field_type_enum.go
  data/frame.go
  data/generic_nullable_vector.go
  data/generic_vector.go
  data/nullable_vector.gen.go
  data/vector.gen.go
  data/vector.go
Labels: dataframe
